### ISSUE TITLE
`

### ISSUE THREAD

**Issue by ghost** [RoboBibb/robot2016#1]

**Comment by dvtate** [comment]
XDDDDDDD nice...
My mother says we aren't allowed to talk anymore though...

**Comment by dvtate** [comment]
I will be writing my goodbye letter on the VPS during this robotics meeting... ( /goodbye.txt )
This is very emotional (T~T)

**Comment by dvtate** [comment]
I will still see you on github though.

**Comment by dvtate** [comment]
the mentor says this is incredibly unoptimized. XD

**Comment by AmamiyaRinyuki** [comment]
.section        .rodata.str1.1,"aMS",@progbits,1
.LC0:
        .string "%s"
        .section        .text.startup,"ax",@progbits
        .p2align 4,,15
        .globl  main
        .type   main, @function
main:
.LFB39:
        .cfi_startproc
        subq    $1048600, %rsp
        .cfi_def_cfa_offset 1048608
        xorl    %esi, %esi
        movl    $1048568, %edx
        movq    %fs:40, %rax
        movq    %rax, 1048584(%rsp)
        xorl    %eax, %eax
        leaq    8(%rsp), %rdi
        call    memset
        xorl    %eax, %eax
        movq    %rsp, %rdx
        movl    $.LC0, %esi
        movl    $1, %edi
        movb    $89, (%rsp)
        movb    $111, 1(%rsp)
        movb    $117, 2(%rsp)
        movb    $32, 3(%rsp)
        movb    $115, 4(%rsp)
        movb    $116, 5(%rsp)
        movb    $105, 6(%rsp)
        movb    $108, 7(%rsp)
        movb    $108, 8(%rsp)
        movb    $32, 9(%rsp)
        movb    $108, 10(%rsp)
        movb    $111, 11(%rsp)
        movb    $118, 12(%rsp)
        movb    $101, 13(%rsp)
        movb    $32, 14(%rsp)
        movb    $109, 15(%rsp)
        movb    $101, 16(%rsp)
        movb    $44, 17(%rsp)
        movb    $32, 18(%rsp)
        movb    $114, 19(%rsp)
        movb    $105, 20(%rsp)
        movb    $103, 21(%rsp)
        movb    $104, 22(%rsp)
        movb    $116, 23(%rsp)
        movb    $63, 24(%rsp)
        movb    $32, 25(%rsp)
        movb    $73, 26(%rsp)
        movb    $39, 27(%rsp)
        movb    $109, 28(%rsp)
        movb    $32, 29(%rsp)
        movb    $110, 30(%rsp)
        movb    $111, 31(%rsp)
        movb    $116, 32(%rsp)
        movb    $32, 33(%rsp)
        movb    $103, 34(%rsp)
        movb    $111, 35(%rsp)
        movb    $105, 36(%rsp)
        movb    $110, 37(%rsp)
        movb    $103, 38(%rsp)
        movb    $32, 39(%rsp)
        movb    $116, 40(%rsp)
        movb    $111, 41(%rsp)
        movb    $32, 42(%rsp)
        movb    $103, 43(%rsp)
        movb    $105, 44(%rsp)
        movb    $118, 45(%rsp)
        movb    $101, 46(%rsp)
        movb    $32, 47(%rsp)
        movb    $117, 48(%rsp)
        movb    $112, 49(%rsp)
        movb    $46, 50(%rsp)
        movb    $32, 51(%rsp)
        movb    $73, 52(%rsp)
        movb    $39, 53(%rsp)
        movb    $108, 54(%rsp)
        movb    $108, 55(%rsp)
        movb    $32, 56(%rsp)
        movb    $115, 57(%rsp)
        movb    $101, 58(%rsp)
        movb    $110, 59(%rsp)
        movb    $100, 60(%rsp)
        movb    $32, 61(%rsp)
        movb    $121, 62(%rsp)
        movb    $111, 63(%rsp)
        movb    $117, 64(%rsp)
        movb    $32, 65(%rsp)
        movb    $101, 66(%rsp)
        movb    $109, 67(%rsp)
        movb    $97, 68(%rsp)
        movb    $105, 69(%rsp)
        movb    $108, 70(%rsp)
        movb    $115, 71(%rsp)
        movb    $32, 72(%rsp)
        movb    $105, 73(%rsp)
        movb    $110, 74(%rsp)
        movb    $115, 75(%rsp)
        movb    $116, 76(%rsp)
        movb    $101, 77(%rsp)
        movb    $97, 78(%rsp)
        movb    $100, 79(%rsp)
        movb    $32, 80(%rsp)
        movb    $111, 81(%rsp)
        movb    $102, 82(%rsp)
        movb    $32, 83(%rsp)
        movb    $115, 84(%rsp)
        movb    $117, 85(%rsp)
        movb    $98, 86(%rsp)
        movb    $109, 87(%rsp)
        movb    $105, 88(%rsp)
        movb    $116, 89(%rsp)
        movb    $116, 90(%rsp)
        movb    $105, 91(%rsp)
        movb    $110, 92(%rsp)
        movb    $103, 93(%rsp)
        movb    $32, 94(%rsp)
        movb    $105, 95(%rsp)
        movb    $115, 96(%rsp)
        movb    $115, 97(%rsp)
        movb    $117, 98(%rsp)
        movb    $101, 99(%rsp)
        movb    $115, 100(%rsp)
        movb    $32, 101(%rsp)
        movb    $104, 102(%rsp)
        movb    $101, 103(%rsp)
        movb    $114, 104(%rsp)
        movb    $101, 105(%rsp)
        movb    $46, 106(%rsp)
        movb    $32, 107(%rsp)
        movb    $87, 108(%rsp)
        movb    $101, 109(%rsp)
        movb    $32, 110(%rsp)
        movb    $110, 111(%rsp)
        movb    $101, 112(%rsp)
        movb    $101, 113(%rsp)
        movb    $100, 114(%rsp)
        movb    $32, 115(%rsp)
        movb    $115, 116(%rsp)
        movb    $111, 117(%rsp)
        movb    $109, 118(%rsp)
        movb    $101, 119(%rsp)
        movb    $32, 120(%rsp)
        movb    $115, 121(%rsp)
        movb    $101, 122(%rsp)
        movb    $99, 123(%rsp)
        movb    $117, 124(%rsp)
        movb    $114, 125(%rsp)
        movb    $101, 126(%rsp)
        movb    $32, 127(%rsp)
        movb    $119, 128(%rsp)
        movb    $97, 129(%rsp)
        movb    $121, 130(%rsp)
        movb    $32, 131(%rsp)
        movb    $116, 132(%rsp)
        movb    $111, 133(%rsp)
        movb    $32, 134(%rsp)
        movb    $99, 135(%rsp)
        movb    $111, 136(%rsp)
        movb    $109, 137(%rsp)
        movb    $109, 138(%rsp)
        movb    $117, 139(%rsp)
        movb    $110, 140(%rsp)
        movb    $105, 141(%rsp)
        movb    $99, 142(%rsp)
        movb    $97, 143(%rsp)
        movb    $116, 144(%rsp)
        movb    $101, 145(%rsp)
        movb    $46, 146(%rsp)
        movb    $32, 147(%rsp)
        movb    $89, 148(%rsp)
        movb    $111, 149(%rsp)
        movb    $117, 150(%rsp)
        movb    $32, 151(%rsp)
        movb    $99, 152(%rsp)
        movb    $97, 153(%rsp)
        movb    $110, 154(%rsp)
        movb    $32, 155(%rsp)
        movb    $115, 156(%rsp)
        movb    $105, 157(%rsp)
        movb    $109, 158(%rsp)
        movb    $112, 159(%rsp)
        movb    $108, 160(%rsp)
        movb    $121, 161(%rsp)
        movb    $32, 162(%rsp)
        movb    $99, 163(%rsp)
        movb    $111, 164(%rsp)
        movb    $109, 165(%rsp)
        movb    $112, 166(%rsp)
        movb    $105, 167(%rsp)
        movb    $108, 168(%rsp)
        movb    $101, 169(%rsp)
        movb    $32, 170(%rsp)
        movb    $116, 171(%rsp)
        movb    $104, 172(%rsp)
        movb    $101, 173(%rsp)
        movb    $115, 174(%rsp)
        movb    $101, 175(%rsp)
        movb    $32, 176(%rsp)
        movb    $97, 177(%rsp)
        movb    $115, 178(%rsp)
        movb    $115, 179(%rsp)
        movb    $101, 180(%rsp)
        movb    $109, 181(%rsp)
        movb    $98, 182(%rsp)
        movb    $108, 183(%rsp)
        movb    $121, 184(%rsp)
        movb    $32, 185(%rsp)
        movb    $102, 186(%rsp)
        movb    $105, 187(%rsp)
        movb    $108, 188(%rsp)
        movb    $101, 189(%rsp)
        movb    $115, 190(%rsp)
        movb    $32, 191(%rsp)
        movb    $111, 192(%rsp)
        movb    $110, 193(%rsp)
        movb    $32, 194(%rsp)
        movb    $97, 195(%rsp)
        movb    $110, 196(%rsp)
        movb    $32, 197(%rsp)
        movb    $120, 198(%rsp)
        movb    $56, 199(%rsp)
        movb    $54, 200(%rsp)
        movb    $95, 201(%rsp)
        movb    $54, 202(%rsp)
        movb    $52, 203(%rsp)
        movb    $32, 204(%rsp)
        movb    $112, 205(%rsp)
        movb    $99, 206(%rsp)
        movb    $32, 207(%rsp)
        movb    $117, 208(%rsp)
        movb    $115, 209(%rsp)
        movb    $105, 210(%rsp)
        movb    $110, 211(%rsp)
        movb    $103, 212(%rsp)
        movb    $32, 213(%rsp)
        movb    $103, 214(%rsp)
        movb    $99, 215(%rsp)
        movb    $99, 216(%rsp)
        movb    $46, 217(%rsp)
        movb    $10, 218(%rsp)
        call    __printf_chk
        xorl    %eax, %eax
        movq    1048584(%rsp), %rcx
        xorq    %fs:40, %rcx
        jne     .L6
        addq    $1048600, %rsp
        .cfi_remember_state
        .cfi_def_cfa_offset 8
        ret
.L6:
        .cfi_restore_state
        call    __stack_chk_fail
        .cfi_endproc
.LFE39:
        .size   main, .-main
        .ident  "GCC: (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4"
        .section        .note.GNU-stack,"",@progbits

**Comment by dvtate** [comment]
I really need to learn some assembly :disappointed: 
Online assemblers aren't working, how do I compile/run this? 
I managed to get my HDD from my laptop out, so I have Linux.

**Comment by AmamiyaRinyuki** [comment]
Just gcc it. And please make sure that your github notifications won't be
sent to your mailbox. You know what I mean.

2016-02-19 5:28 GMT+08:00 Dustin Van Tate Testa <notifications@github.com>:

**Comment by AmamiyaRinyuki** [comment]
Delete everything you've read. Including this issue thread.

**Comment by dvtate** [comment]
good idea!
