### ISSUE TITLE
untitled 2

### ISSUE THREAD

**Issue by ghost** [RoboBibb/robot2016#2]

**Comment by dvtate** [comment]
He's not here today :disappointed:

**Comment by AmamiyaRinyuki** [comment]
arm-linux-gnueabi-gcc

**Comment by AmamiyaRinyuki** [comment]
You may need to create a pair of GPG keys and send the **public key** to a public keyserver (e.g. [https://pgp.mit.edu/](https://pgp.mit.edu/)). 

Writing messages in assembly is not very safe since it has no encryption.

By the way, I don't know the real reason of your mom's behavior. I said that I can provide many things that can prove my identity, e.g. ID card, IELTS score sheet, etc. And my company's information is available online for anyone to verify its existence. Assume she's not a racist (according to your friends, your neighbor is a Chinese and they get along well with your parents), I don't know if there are other reasons.

**Comment by AmamiyaRinyuki** [comment]
My public key is at [https://pgp.mit.edu/pks/lookup?op=vindex&search=0x60A02D569229C982](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x60A02D569229C982). 

You should encrypt your messages using it before sending to me.

**Comment by AmamiyaRinyuki** [comment]
Some other suggestions:

1. From now on, use **completely different** and **long** passwords for your online accounts, computers, and screenlock of smartphones. **Do not use birthdays, people's names and common phrases as parts of your passwords.** Remember: For **security** and **convenience**, **you cannot have it both ways**.

2. Make your computer's hard drive and your thumb drives encrypted. If you have insufficient time for re-partitioning, you can create a small disk image, encrypt it, and put your important files inside it.

3. I don't know if it's **legal** for parents to **spy** their children's online communications and letters. Such behavior is **illegal** even in China.

4. Try to predict others' plans by observing their behaviors. Be careful and don't miss every little trace. Take precautions.

5. Look beyond the surface. For example: If some unexpected incidents happened in future and we get lost from each other again, you may get some pieces of unreadable words in your mailbox, your github, or anywhere else. You have to figure out the meaning of these words **by yourself**. You have the ability.

Don't forget to delete this issue thread.

**Comment by AmamiyaRinyuki** [comment]
I'll try my best to earn more money and create a branch company in US as soon as possible, but it still will take at least 2 years.

We will have a bright future definitely. God will bless us.

**Comment by dvtate** [comment]
<3 I will encrypt my messages next time I get on a Linux PC. I've definitely been maintaining an insecure system. I will be graduated from high-school in 2 years, so that would be the time for us together. I'm not quite sure for her behavior either, I can understand her concern if I was a girl, but I'm a guy, and this is an asexual relationship, so there is no possibility of any harm being done. I'm really sorry for all the difficulties, it's mostly my fault. 
In America, children are considered objects of their parents, however, I'm not sure what age that cut off at. Parents spying on children is perfectly legal here. :disappointed: 
comment after reading so I can delete.

**Comment by dvtate** [comment]
if we could go to the same college that would be amazing.

**Comment by dvtate** [comment]
If you were to vc my mom, I think she would have no choice but to accept. I don't know any video chat services that work in china though....

**Comment by dvtate** [comment]
https://pgp.mit.edu/pks/lookup?op=get&search=0x6F2A2521EF7058AC

**Comment by AmamiyaRinyuki** [comment]
Did you encrypted your message using **your** public key?

You should encrypt your message using **my** public key.

**Comment by AmamiyaRinyuki** [comment]
Ahh, it's my fault. kgpg does not recognize non-gpg encrypted message. XDDD

**Comment by AmamiyaRinyuki** [comment]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMA2CgLVaSKcmCARAAwowsKW0wxMxRgnjjZ9LSKTJcyrhb6Xy+LQGnNZuXjhZ7
E59LGxtFamJp38VkXntdM3Kpwv1jW4oSRSaxHhTL4Bodddr4eNLP+9KxNrL+h3CV
y+Re7mXcReH1JXOiZ/DZVLe34hYkffmyOQZS+SngPP2KTP04jxmdxMj+cMq02dw1
Au3XtErUtCxVBQMnijtX7qPfPJBrUgG2az408Jxv6wgg30iC1EnQUv9id9l5vVSL
Qh5a+jItjJ3kmDpSW0CvPxvGd23BKj3sC5Cx44yCTQ+jWF6ZBjkHdx5Q8zNWdDhn
W/JN6+sPCqQUx7PazymsmkDQgxK4VPy0w1SVhMGlX1ewWU6z81R3ypauUcc+/lWC
LPrPGtqhluR1pZ0tN/TlSz15LqnLdiModf1NxyUSN38y6iO30ulUFpCfAHkXRUNm
cWiDq86jteQKkTmgkslxlpYF/rhwPE9EZGupIBm0RJDdHS3/eb0RAbIiIo3FVOVy
OR3t2jRLUNlPALw1/RM/SJXlK5dCkg/jWVMwA/iMJ/bpI+w6hbpsKMQ+0FbfWo/f
A8zHBMc0bHi5AsjvktTYO7db0mztb0MJMqhT4LpdkZpa+Ea0Mv0KpdUvHPEgtBZC
3gZ+NMorCn6rz8m80bS5ta+qdDZtVRdZlsciEpK+YDgtyx7jNSQ+csVztqo/1UzS
wPEBc3+eWTUM4eTmTzpdmJcnXQ6Ud0mlg4VYg8vzH1MFMfGzbTDyuRsQgnJv1DDY
WGqYX+jJRlTMRkpCprDZ2oasqbwYhIlGXKVWtrDdtF0g6w+q+5Fb6i2xKHuTtRW2
ZbJB2WKGPjkmN2z11hRWUNXXDaB6RucktEsmXXTNtpROF9nP3F5B5IqOejla0+RT
wsZHxvavuDWn51+nyQXdix1jiELd3HeLEk8E9qv4WBuUTFrfAbTcxva3whdIon9Z
b0iHy9eF4BeEjLQonbmZ4JW1UF+592ZnKs7BGyssfCF142DjUX8nOdqBIoVTXNs3
27nFMMmTmo0nyZ//AEKxGRYb3zT1A8fk/Xv1ANIC35PQqt4eAp32tGf4pTydkK2j
RSk4HT4aqY7LK0mreAPUQJBCwD1GvmrVuw0aC3VSOvopMXL7kDenW00LdHS3Tj/7
uuOc2u3lo0QOrPKcX2IiOBml//vqLNWSIwEoLAZnElZfuvXUVs1AILguJH7lcAFI
RYEeDsThfK46XVSJJcebZ0ozJpgtQVb98naefe18nRTT8rr/+nUCan+KNeGGvFFE
3rec
=JYT/
-----END PGP MESSAGE-----

**Comment by dvtate** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA2CgLVaSKcmCAQ/+IlJr2sIFMvhdPXSDE9WZUK33DWHtobzNCWmOwTpLSgaq
RfGX95G1scqMPf2DSIshbt7yBU5MTcpQLo8WN9LVdKX4jBf0JUe7bfSJzImLW6o6
bJyEJv6QcOdSfM4v9rCDBaw80mhIE+gv7aAeiEsNoWb/KqQfuQ4K0SNwALDED5ES
cRWjo7QcnJyDp/efV7LfcHhKKT+bqeWPuCwvtraGcFaFfr+bZYZzdXboto1x/Y0a
ZcQKQBWl1PAKkwKEuBPRY8OYRWrAx+3hXqXvfn8MKmpqYuyCZmeuigGtvb8Ul5mv
5Tx6kOlReJEAYcMsGabFxZv7bgyROGYEFZ9oFC9sT0nD+5pucddadoDoQzLSaMCi
mlC9Wf+hVzgygwJeEB2tbQnB2QWKE01gbmhDIE65KNoNLKElM9ThQ9Eoi8Zp+pUa
MehE5vHcQzmDWVSqRLfHKfidS4HcpCgq651QvNNSbvPbCvZUiD4hl1kP4rUPJlci
KCxOdZdDGEa+LrHGq2Gby8vsMg/hkwpMom+OkHERHGxwJEKRyrNKtoMyrIZZ4/9o
Nj9odHs54Trm67SFOAAjM3c+EFioI5OBZ2PQa/z0BVQL9QKEOtg18D8KFOywGjcX
Stm0qn5dRz2QgqoaSAW7BTE07gT1xdjbxxOoJrRydQpNPFs5jblaztSTy3eadzvJ
wJs7OLvdT8LcMldtzLr4UEpG4N8mmqOhCb95brbMtY88FaKQqhJJMPQJeOd5t/Ji
1m6ByVrzW5mCWrqmHcu4IWqwJosWtPn52WNU8JBU4dnLbup94f1PAI/7DlfjVrUd
Kmol2cgt4WTNl1r6qZSvpmiVG4yRPSzUz22sCLnRxbaXFL7KLl11Fck/KhslrXr2
MpIQifMEVCNMFtdTL6GRzh7sh7s2viVnw3Ak6G+OROhylT3URTqOpuAKXphdVjG4
dQtWp/IvMUc5GNtgS58Nm/rXn+rKo3UiHISWzlURE4nyvixY5ckur9J7L9c3Yr2J
dgR8qh2Ser59uj+eHz7GR8F8kUxI9lOTvN37dgSc6SjB/W3KWTVNBBIJPx0BZVe6
O1TbHEQd9Xu8fjFq+7VODvJaunGBecPSKuQ2okaPxzdApgJYK66lE9sAnggMOiZT
UH+77QBi8xrkveEUUQ==
=nYHI
-----END PGP MESSAGE-----

**Comment by AmamiyaRinyuki** [comment]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMA2CgLVaSKcmCARAA56iNUDIu48EcL9X6lTswzByAKR+5zm9Tw37Oc2CHXbaA
Cp2HCEfkfy7tnd8Fbo9AcZ4opkLLLJ/4HGMVEKAwtEVOToBDn0A/52OLFx0PkdkJ
B1pzL8ZR600k6wRJtPjTQao8TYii1rFZ6lYb+GoeemPpis4Omb1nP5FjCC6M8ERX
pRD2IrwuS68A8MsbemtW6HT4wBHlUCJmYfiKbB10uqUrfGbc2of4XhXALjLLDq0K
m+QYtbL+s7fJmZGV/RZ2Kwi+qCrohjzq6fJQzGQ4lZ2toaeFGauuSkT/C7cK+rVY
tLHh+duqsOfA7aO2lGBF0CSjdDvTazA1L2F8yYUvazc+9kLtwEuIIqmt8C9mu9RG
1k8w8dxcuVOYSTSkNxPYxcGl6bOGrpEA+pe7cyl9CShq094jB2IB2ZWakyh710BL
Z1XsHdvwpZnzOvvI3dTZSPnloTRvVQyFAEzArnIVbot7oXy3n88ArlLNSYgAMx/7
GOc31OouXR7bsyHvl0+tXAOIZ3X6s57xFlSSJ8laZicGr1hnFSO9VWeICo0/VloZ
MNYg56zy0j9qTUz6t8sPAoI8L3LZvqPxvVYJ8J3CACtX0ergjehhmP0QmhwqgTtc
n4HMNkssmeUxHuoE4/71uxvjUI4sY29Cb4R1Ljbruh1PpuURRlsAD85P7m9hsf/S
hQFneXaN7qYnATD6JzmGibus+L1LGV6enni4dR19Lyhpoob9y0CRK75zntdEdRSN
UKCDbQLomm1PfRLEVdOvuBL+N5IToflzH8+dxsCOInvOsseMZRa3/q8hhd0mcMqi
FGfHiC8D/Sr3Jzjdxp2Ue66oN75cpzjHDCNTZ2TDabhUSKfjw5k=
=gvfR
-----END PGP MESSAGE-----

**Comment by dvtate** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA2CgLVaSKcmCARAAk193tL8q31FN0HrXsA3YYAOjeJBYkQZyIpZjhWfAcASF
G1Qdkgrqq0Y3snIxTgEKHfUwKxK8P8A18GBkBtMbab3NO9f1jVvdBIvUPmmZIjEw
hyGioPlHH+3DGVZQto00maqtEE3F+h5FoWIb/Zs2EmFjHru4u+lEGVSHYw5hRO0j
3qsdHzmO9xAiMUDG55OeDUWIFEhXbW260Nl1Fayw1l087+K69xE2lFLpbGc8EPnT
stxjOm0A3Rd6VLOCw/qICZZaBeGzTM5297qh2SDcPEftzCpTzdy3KpcmmoL5vB4+
dad/hOncIN46D6o0GV6USM3nR8xhFQxioIJ3vRq1iz0kQKeiHuD8E4jrNo9q+56l
N4WhmmQENR3cr94oF7k96SaoYg0zPqPz4YHEWtCdlbmcW5FEKS2Rp9M0f+5pE4uj
BooNGRIPNkI7JwYV58k1uQbMb8L1x1cX0qigISqLv/kPxQVkgOW6ol37N+VpRty8
L1C8FAFhtCemkdkXoxAY85BG+QURDcLpqq2dAP1p3tguZ50V9CKJEAwYSffBZgp+
p/MKTo9OiyGfHC2FpEmva/tEzzmG2Xzww0RtRI+OhY6MZ0uAmFoXuEa4BBnR6lrC
zBnsVp5ghoaA/n97s8qZWkWcJ1tTTs99+l+UQdAHZJxmOk9W2Qqlxsl3exu84LPJ
wH35ovmFwdBGx6UjsDqf382a2lgTz/dyy8fHzpfrX7EnhQ4IXzo+VV3u4VbYtkSN
FUzWk5hIDEq7NKE2kW1/cGbXbqYqQSWl6iaD1+T8fmsKmWky36WzXV2CQGvDyyHr
WyIQZ8wiR33RTKLApTODONZJVT+B8ut/YGnMm6fkLpajMVhDWgvoSumOdcjUe21t
Ao7HrrodVf2nW2Owz9JcSp2UTBFwxvhm/v0yG49/SD7IvSJitUBsjVq41gvp+Z7L
QoEdhALSy1u1s3xFu+ZlNnWgWgXoJyeF4WpMlT2Pvv5Q8KePqA+D3ZLwrGCCZlnz
B83/90jfPJW2HQy0Moge8v6MHdeSEMd3BG2/7vDUGd8xfnMZUQOcOFuZ0pFpYzfA
vVAdIisBR3xr6zMyEse9AXpvw2sv8HrKA1rb1cJTtA==
=VJ8m
-----END PGP MESSAGE-----

**Comment by dvtate** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA2CgLVaSKcmCARAA1kDD+TBiDoem/ayg8sXWZVdamcjrVJSksxH8BNBYm1AJ
nCgeceWYW6BwB3owEqNFN5CtPxdjvaz32dgStwi+kIHc5FXKvNur9WXwPvaNTw+4
P0sPIQi67UDBKIJ7j9fMhw8cpFLWFRkRq0iH05W3JhBbvMYTGjsGI2YjCcjboRTH
vv1btVR9rkaqb9HOwicw/2NDZOAq5RO4/FUeNBqQCx88Zmc/g8JIgVZlf7deaS8D
1CZD/AJOx+gf7KHokurh3G2WGa9EyFt1aie1RZXSwzlA1tvutwVYJHRKp1CREQ79
Ay33IGUV1feicMJoOf2pdqWAFY5K/4tVOLRVrVQE/pSBNON32M2GBYnRrMNUxP0I
Oe/uiMLfL2dtbXiCE46X/5xVOb7nI3iJDvwsgv7wIDbUEIKAUhSiDLCoeXCNb2Qw
pm3hDWj6iSlnlU//9k3H6RaSBVp12RfP37rmpq2ntms6n9u/ZmbqfheaOz53OxZU
PQjmlG7wY9guXKjtK4S3gsl3H43dPnm91yMnPDzCNRLrtW1YY4Um+R9WTCEziYQp
TDNEGZAwLc8UGGTqjpsA0+/h2wKak6UVEYieZBS+O2ZdQq2GVEFpDxkiikDSvIJp
EnDzmcDthv0PT6W30fAK5dx4e8GbBq8PXheiTT83htPhk2ybS3bu5QCAu4aJ14bJ
bTtczNDUxWPexsMqy38N6o60zMg8qv+3K7yUBble24eQe5SI9FC7midx/osCAgRF
OJDzLpAqRZlmfCxdpmVJ5QMYdwTq202Ba309Mm9vhjpnbdgFAdl/6eqaeZbFfToY
pKPOnQXUKk/OBM93JQ0=
=jxp8
-----END PGP MESSAGE-----

**Comment by AmamiyaRinyuki** [comment]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA28qJSHvcFisAQf/XZ+gVCqTVHvYyv/gUEbsDs/hyvPYDZEACy1RdyGmp7WH
rEygKjjNQ13VwBQs4nrBI1UaMOdsh+NGlX/CI+j51YYmWox+j6dtt1eM5M/8My6q
gkIGJ7ycUqJnPtKCZ/WX+lYjHMs4MjzeF1/u3I2OTlR/njNJn36dwqsJ6HXlXitn
SyufN7XspFwVqu4944olGvw8FbHHEcUtjwCw1fVPShxtJGHIGWtt1UOGUK+jAn5H
HTHDZ7vF6LPeyxlsl0+oKvA08vglBQzw0+JQVUpHQItEMGHeTE2LWiwfX4Wnbw7B
fV6aRV64rv/QMXghDU9JUISZSZLLFN6eES7AgRhBZck6iTY69cFnkNH//P1pUQaX
j91ZiHIjulJRc9511huG9fdUFDGd3nCuwPBYkj1unbHD4sW0M4POoWJTnQ==
=bHm9
-----END PGP MESSAGE-----

**Comment by dvtate** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA2CgLVaSKcmCAQ//fa2qsuWRLJZqxhwDKkrj6bNro/Y6CI/qRzzGl/gB/BJP
3HskJs6YCugQv0UHHIvvDWABIefxAlsKQlT05MT6yEeP4LVfMbABtBOvISszwBEU
IuhEQ+yndOwx+ljW/+OSQZ/qyaRHM9DY4f0hIueYf5bqkcR1gziLPz+a70/QjWFF
KPPDzuUYYhQeq1vTXGAbMVUKZiI3JsA2+Ivgg1LuaGXmOb/oFs17rp4Bw7wzjLJw
Nfc9RFXTsPSYrkGHLsW35lMq3338kSCMVsgWs1RWde7pUf8AYgpOVdRy3cMlt5AB
ZflKkEbRZDQMPFH/bVVe2FVLsirg3u2GnPCdFSyRiAbEElbYVc2tgPaEDPcJ33T3
etAN/INA7HX69XOJ9idLrzwUkFwo4RTJDcpbakKkKS7sei91D7J9ZPOIjL7yw6d9
btPA08EWxQs/z8S1Z7qm2GZHGpTIchDnxQS+8ifbGyBmXLkLslC9fSwYZC/iSzSF
mIyLTqWKGmmhCClnclPDIDzV43PAcrMJ4M3x6iaEEQnKYqiCII/xuAPfLx/4cWKB
otPZDRZfOmgP7RI7POY+nWsrnE+cM+ay13kQKHr6oz+dq+OLcnlWP7RB0G6tR5t+
rTnAcKPTkflFucLT03UbDwyS27pkDhg7Mby2DgCII8XMTM5xSHg/CprvFntKOEfJ
wZflpDpJAbP3oAXp8aQCVokQ525A1oHFB1YOLgmi5nvGSpATk2C5Um8RYCoPWCoq
mfj8VTPdcFckkvi9Y8Jf0ZhYUZmmA8fItZG+mX7utxIAu/O/eVhDu8ssWGuFJLpK
5XNLSHauPSfldHd1DWELX81+viEpSLWF83nHsW205+i6cL0R3OfriGf3KRL5oivL
TpzSTK8NmIhZUDSLNbm0Y3Hd35nNJRn7N3ddHYlmqL3LMqsVVoZJXubKr/cQmcu9
wzG3F9uVW5rCIsoeSYuXvbLj9KREbi5UB1ZsJCqPNFgUUHUaBZ6X+NWA7trAw8b+
C0QoQfmlGZcZ90GKk/RGx8SqyiT3SH8kG2eSSFbkM/6dbR/kwmgECDRhc/bp6QBU
4jcynGuXvzR/d0Y7MflUk4BMcM8lqAEf4xCjrbMv6xy948asniEFhRaFqoEykU4N
CO33EIiO4oBIl0O0x3T4KlYEilUW11Q8VwDsULb7LYllJryoa+W3et0gVZwD3gkC
Wz+ZHua0PP17mYM0oy6qqTmBQRNCnngaV5mKoAdt+vRxNo2IOaJpqXaY6XRHnp2H
UUtkqVe9e8owq5wKhmFztRthPDMT7cma1OtdSjj71NvlA848+uSKH8+yLRzHoA9K
1daBqeTiXNfw5LL0DJbHNGBR8ExR6kW1nSK5J+KQTmvSs+rThuBnA8bLpGCMBqJ3
ER40uJKG0g3jHElGIbuIZC9CmRxYBeAnMstVLywKfUP/ecJLPH5rEWwnV6dhGmsx
261epYV82bIna8/bLZuBCZq1QIv3kPV6sQ==
=tEqZ
-----END PGP MESSAGE-----

**Comment by dvtate** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA2CgLVaSKcmCAQ/+Pctit961hShEGm6py2iQmbHfilYdZeddZwFNq5rg8wWC
jKeSvBYubOacR77j68i7hmxlp7aogcx5SiBlwr17YtKYUtMcS7DCgiSCHyaoBFIO
bGTImOYaToSlXfWNYMuseJhTc/s/P4DqWwKKmGZ+zKVbC5Irn6yxr73Jz+GeCrw3
VwJIctmLLhv4MRigdDkk+4GSWjXRvcDb4vsBVyucD5qZ9focZI2rxQ9j4vAg/GZP
2fFSPwvUv3wBjBngQPacLNVrIcu/x+bkz+SPdRW5emk+F/IQQmNT6Lpodxq8zjjf
8QNu9Mxu3jDqoTacqYmLhzMwKFSc5M3tx3arxpU9iEMyJYtXvyme/l25r3Ft9b7J
noP/LsQefULMFRYr4uWpOy2lJGiOFgefy244MsuhQ6va3sXUfDfxHSvfG5uxzMiO
Dj1C6vXTWKQRkrErmuvbJHBjN/oilTlLTQsrH33Tl1ec0CNnjqWcSpJMZbVTUQeL
+c4H4F4MMT/jQbsJA8jiutdciRNnZTCT6diP3NZvxrzOJWZUjhKSGZFb3Nu6bRbj
GqFbo7tVgGZyu7yQx3yHpc31VHx17mXcc8/ZrbgNasfSfzeDviWf8YyaBlR3fMK1
wSeFdWxiYctcZ9z37tt/5HQmRFgj0sSzGQBW1MaOUw+d9+TqI2fD3qi+CTyzihDJ
wHgdjpPQiI2yGopKauVfRzz38Mp6XKUPrUSZTltUkNcKV9XVYEatbrb4znzTkZZ+
j6Ysek9y99NywEJb70Vop4wRmnXo9Cgyh834Wfw3nL7FPyd8hG++5zn5l8DXRZH3
aaJarEyaVo1iJrZ+/zQc2DAit56sLkkguUPqAonP5N4lDQT8uZO7Sfw5Gvrk1Cwz
TZs4hNisssM7V53bBE2Jh6dxz3x+WecNy2s86t7ye4LngXVUFUkEPrvvnDRHzPC2
4pHVtjI+ieUzXpEBtL1ZHI4jCZCO18VqSNvRhqi2Cg7QzWD5aXYdQwwZBHa00kOa
yG1VpBKkccAkPx5tm9/0HZY4j+/0NKD+Jnl0Y3VrgaUI9QdLn8hTnQywwRW/DOxW
HKouf1TEOTiqMXXjmDI7nf+r5tmXMRLwyD0=
=nQgs
-----END PGP MESSAGE-----

**Comment by AmamiyaRinyuki** [comment]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA28qJSHvcFisAQgAh50X/LJyHcOEp1KOpjw1PCjsCge1jvUWG0sTKTsQbqoy
5HHRJu1b6uCrwrd3/SyjCIu6Y7CIfR6QXuyk/duXm2PvPYovndE4E9pCXTG7qFW8
w/+GPtnmvQBQWKMioqZy+XXBM0u9hCDUN5UTrfranHzb8nlbZkMlI4jmySYouo1z
c7VYMebSeKcmCnHcdAQc8dV+xYt4Hl2uS99ITFWfJk+eyK3V0IN3yB3tJzQtdo43
teMNWDt2yt+GHkSQ3tFdHNZ2t67JgN8hNNB4H6T5mS3yCOR2NyDnpWV/PObccfTf
li7kcZ5UYpTcgmeP+EfbJHKTTCmegeArUiW8elc0VsnA8Rukt4RCrayJ2vDFlYxX
1ExZQbCe3Orx4UZ4T5cz2gt/up2huH3Pxnmud2FkLR0m6IC2YUr0yvKe46duHJ2W
KFOWT1UX8XenTMpYS+hlKi7yuUJLzvfVvw7niudMYNFZ3eoduuMWODPc072KC47N
v/VS4CmkImPPX9EPrPDmRiV11g7StgqqVPUAGimeZWRNKdwY4yECMcr8Y2IUBgaO
I3bHVgnXyqJgKuKjWAMuQZePFr5iy0tCLBKf2MMHJeVyTfC3twlL1PMmtt6rqyAQ
U6MEh7nbM0J/Pwr2ZpGzGmfKmieAo+h8tHKodztZwJGJCuxaaWvppG0CZxCD31Zx
bPKdtPcBGHg8K224Y/3bHy+UJxY142zOXiPy3VVctQ4ADuU/lgMaj0woImVFughh
Wb8kKuErohBQTvRbKBDeoAa5N7xHWhJSnXfShmE0XlaA63vQRQRfeehTRXGtr8vH
eNJ4Ldh+dg+Y90EcI9ZqL/aqOZsqZzvlXLYRrCtiAJeJZDbJoMWXyrDcr+q7kdJy
6uQvhU/OHMNSwJ40E/PktT/FMlzujv2NmNX+M2o/NkIbY+I=
=6HJs
-----END PGP MESSAGE-----

**Comment by dvtate** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA2CgLVaSKcmCARAA2cENlXoraKLMP3TM+T169i2ynporuzWEJa79lfe3MRgh
jkHEeKxmPvi7OmQ3FpxwOBhlkfSpdg7n6mB/ek2tbNvxshApFpYRakniOqj181dQ
341sAq8NpazLnhVuMucbE9GJcR3Wr0IcTT3KlG2t/X67YxmNB6dGQwl+6zNqufa4
PQTJj+Pp4LKdmzdAx6FtRbbnvihob7+auPU9KS8CToWdIk53YqLjTxQE2OClxEEl
b2jM4nSsFIzskxg9xucn0HFvucPaJQ3Hpjwf9EvDec3/NxZRb2w+faV9yUCp3l+5
FhrxB4JtSYygNnlxwakhn9RFifm4bxDU6a4smj2tfOygS7rnV0ZPI4R2H7YsFqvl
uxY/VdHljU1P5O89bIL9cuZdKiqbz/qm4WCnklYEYDigDQFsgLNcWeVRF58k70Kn
4T4goScvGxygJCSMpM+tdgbPsyx3TOPv2R/vRAHUDbqRIEDZAIn2kA/BC+NRBjgN
drfBZTsYJbPtQT499lOCUZSdKwhKi8Os6OFTxvDB6pXmV85vax5Eo3pvIM9Z7pAp
BlC0oVS1NgH2bPIvMjYc7Yvd1pMYXRt0mnjCdYfCuF76SjVY16XAxbGC4SLxOIzN
MWjdKTwqgLuS4QTCjqEw2ZBcl3tP9r2WgCsesWRKrDToMMMuoDqM6MB3AnCAdkfJ
wanMSoP9VIK9oq66X4MNa9mm1XDZz2EZQrsoYQ11t96EqK+kr3jIPGqSPV/yXMqS
tslEoOiZD61VIHu8gXBH5BnCytLxOxw8ebFZUxAwnvgRyG3RG5EMVyDLNoEf9vCo
JKETtE7XUTiaRNRjuK5v55DTCm40q5Of39wHl2ts68ZLMchsEjlK5valt5k5lg7Q
Q18HMKATaQcwBuxxeXuOpqKG984Ile0o1eoQyykBodMGurJ7Z+uEiWaQxsCLDuPt
RAR0ioTw4cFdYgLdDQeQI2ydbQsGMPSKoBXOjAfKt1E61x7kuegS8ygwNAs9vMEe
ojS0Sr9O1TeC74+7bRIo3sxyD3/K83jnvWewo2NVH7vzvU6QR8tUz8kd7P9HLutM
56vCSnRaPxrXbmIuuw6PtZhafc/FaaKiUmS5/idxZInpT0AOmD45dtZpZ/bujFsn
EtiOyQqyzY9uywXujBGdQblHJuRr4BVdgs8grDraxqc5na233emvI1Hh3vzu1zK5
McFyTGDJctJelf5mifDN+eiKoBUXhQuN86dD7JAUTa8u0BmPOn46Pa/qp0oRkDiw
CE3ylYp0lenEYpJGz/utZef6VJt+iv35AEB6iGJebAHhyXjsdga0IfcywaH2Q8A3
FqbQK0RvbLFrjLrBm0mJfRNvKc8Qq4BCdx/TAoPsy6Q8BQEdnyjuRZAJvdu0ijgh
KHySUJ2m1GNYhvPvj11PXvR9WFVPyURZi4zRuZ9VKbPuqqYlqr1c/gZ7fI0sZ28+
OFIYeVUTvTf4v3OD2VmLmvKsicHfEJlu/oX/j7y3eR5mP6vrEuh1ia99PQ==
=c+F7
-----END PGP MESSAGE-----

**Comment by AmamiyaRinyuki** [comment]
I have some difficulties in reality now, I will try to contact you within a week. now I have no time to explain

**Comment by dvtate** [comment]
ok
